{% set name = "posydon" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python>=3.7
    - setuptools>=38.2.5

  run:
    - python>=3.7
    - numpy
    - scipy>=0.17
    - iminuit>=1.3.7
    - configparser
    - astropy>=1.1.1
    - pandas>=0.24
    - scikit-learn==0.21.3
    - matplotlib>=3.0.0
    - matplotlib-label-lines>=0.3.8
    - PyQt>=5.15.3
    - h5py==2.10.0
    - psutil==5.6.7
    - tqdm
    - pytables

test:
  imports:
    - posydon

about:
  home: https://github.com/POSYDON-code/POSYDON.git
  license: GPLv3+
  license_family: GPL3
